#ifndef LOGCATEGORIES_H
#define LOGCATEGORIES_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(lcApp)
Q_DECLARE_LOGGING_CATEGORY(lcMainView)
Q_DECLARE_LOGGING_CATEGORY(lcQcView)
Q_DECLARE_LOGGING_CATEGORY(lcQcService)
Q_DECLARE_LOGGING_CATEGORY(lcPlaybackView)
Q_DECLARE_LOGGING_CATEGORY(lcHikvisionSdk)

#endif // LOGCATEGORIES_H
